spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/qa_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

spring.ai:
  openai.api-key: YOUR_OPENAI_API_KEY
  openai.chat:
    model: gpt-4
  openai.embedding:
    model: text-embedding-ada-002
